### PR TITLE
fpa: async store, refactor, fixes

### LINKED ISSUE #150: Error in embedded mode after restart
It seems that if I start fil-toolsd in with `--embedded true`, then stop it and then start it again, I see the following errors repeatedly:
```
2020-02-26T20:16:31.327-0600	ERROR	index-miner	miner/miner.go:186	error when updating miner index: error getting last saved from store: getting path from [bafy2bzaceakjdzsnvf4u6cpxow6c6behspefhvus5mpstvomwme5v2rpggw7y] to [bafy2bzaceamxgcuzqh2sntpqpsq3t2bz6m4b5o5flx3txlkhxdta4sqcylblk]: loading from tipset {bafy2bzaceakjdzsnvf4u6cpxow6c6behspefhvus5mpstvomwme5v2rpggw7y}: get block bafy2bzaceakjdzsnvf4u6cpxow6c6behspefhvus5mpstvomwme5v2rpggw7y: blockstore: block not found
github.com/textileio/fil-tools/index/miner.(*MinerIndex).start
	/Users/aaron/code/textile/fil-tools/index/miner/miner.go:186
2020-02-26T20:16:31.328-0600	ERROR	index-slashing	slashing/slashing.go:148	error when updating slashing history: getting path from [bafy2bzaceakjdzsnvf4u6cpxow6c6behspefhvus5mpstvomwme5v2rpggw7y] to [bafy2bzaceamxgcuzqh2sntpqpsq3t2bz6m4b5o5flx3txlkhxdta4sqcylblk]: loading from tipset {bafy2bzaceakjdzsnvf4u6cpxow6c6behspefhvus5mpstvomwme5v2rpggw7y}: get block bafy2bzaceakjdzsnvf4u6cpxow6c6behspefhvus5mpstvomwme5v2rpggw7y: blockstore: block not found
github.com/textileio/fil-tools/index/slashing.(*SlashingIndex).start
	/Users/aaron/code/textile/fil-tools/index/slashing/slashing.go:148
```

### LINKED ISSUE #162: fastapi: make operations async

### LINKED ISSUE #168: grpc: cap waiting time in GracefulStop
I've seen when grpc Clients doesn't use a time-bound _Context_ for requests, and the server is signaled to stop, it will block forever waiting for `.GracefulStop()` since it's trying to finish all ongoing requests.

Put a cap of time on this graceful stop, and force it afterward.

### PR DESCRIPTION
**Pull request by jsign**
This PR main intention is to create the concept of a _Scheduler_ which is responsible of enforcing a _CidConfig_ for a pinned Cid. This work is done async since it's usually a long-running process.

All pushed _CidConfig_ are transformed to a _Job_ by the _Scheduler_, which _FastAPI_ can watch for state changes to track it's lifecycle of execution. More on how things work in `fpa/Design.md` document.

This work lead to a ton of refactoring and adding more structure to existing code, since we wanted to have multiple points of flexibility. This lead to defining multiple _interfaces_ that allow more flex implementations and configuration of components.

_fpa_ work is still an ongoing work, and some interfaces will come into more final shape in the next PR which will target pushing new _CidConfig_ for already pinned _Cids_, and more retrieval APIs which will transfer data between the Cold -> Hot layer async (since it's also a long running process).

Most of the `fpa` subpackages are covered by the `integrationtest` test, since those test cover most of the important functionality of storing and retrieving without any mocks.
But since now most of the subpackages have interfaces as deps, could be mocked and have more fine-grained unit tests. I'll add more of that once finishing some missing features before deadlines, and apis gets closer into final shape.

---

To help the review, I added multiple comments to add some explanation. It's recommended to read the `Design.md` doc before review to have a better mental picture of how things fit together.

All files in the `fpa` package (mostly, all changes in this PR) have GoDoc comments in the exported methods, so I'll be less verbose on PR comments since most of what things does is explained there.

Some deleted files have comments to, so don't miss them!

---
Closes #168
Closes #162
Closes #150

### CODE REVIEW

File: fpa/grpc/service.go [hunk 1]
```diff
@@ -104,9 +112,24 @@ func (s *Service) AddCid(ctx context.Context, req *pb.AddCidRequest) (*pb.AddCid
...
+		return nil, fmt.Errorf("watching add cid created job: %s", err)
+	}
+	defer i.Unwatch(ch)
+	for job := range ch {
+		if job.Status == fpa.Done {
+			break
+		} else if job.Status == fpa.Cancelled || job.Status == fpa.Failed {
+			return nil, fmt.Errorf("error adding cid: %s", job.ErrCause)
+		}
+	}
```
Comment (jsign) [inline fpa/grpc/service.go]: Since now pinning a Cid is an async process and to avoid that change going down the path of the CLI yet, the service watches the returned _Job_ until:
- fails or gets cancelled (a state that yet doesn't happen, but maybe will): in which case, returns the error cause.
- succeeds: all good.

So the grpc api still behaves async. I'll wait a bit before making changes to the CLI until the next PR that allows setting configs on the pinnings and retrieval gets in shape, to avoid wasted work and think about its final shape too.

File: fpa/jsonauditor/jsonauditor.go [hunk 2]
```diff
@@ -1,62 +0,0 @@
-package jsonauditor
```
Comment (jsign) [inline fpa/jsonauditor/jsonauditor.go]: The concept of _Auditor_ was deleted... just because it wasn't something completely functional yet, so preferred to keep things clean.
The idea will exist anyway, but I suspect will have another form... I suspect it should be something that wraps the _FastAPI_ instead of being a dependency. Mostly how middlewares are attached to HTTP handlers to add the functionality of logging instead of getting in their logic which is a bit annoying.

The idea is to have some metrics on how many times cids are added, retrieved, and a bit of audit about a FastAPI usage. I'll think more about it in the next PR, happy to hear ideas too.

File: fpa/manager.go [hunk 3]
```diff
@@ -1,85 +0,0 @@
-package fpa
```
Comment (jsign) [inline fpa/manager.go]: Moved to `fpa/manager` subpackage.

File: gateway/gateway.go [hunk 4]
```diff
@@ -12,7 +12,7 @@ import (
 	"github.com/gin-contrib/location"
 	"github.com/gin-contrib/static"
 	"github.com/gin-gonic/gin"
-	logger "github.com/ipfs/go-log"
+	logger "github.com/ipfs/go-log/v2"
```
Comment (jsign) [inline gateway/gateway.go]: Just to make all packages in this repo use `v2` and avoid having two major versions.

File: index/ask/ask.go [hunk 5]
```diff
@@ -46,9 +46,9 @@ type AskIndex struct {
 
 // API provides an abstraction to a Filecoin full-node
 type API interface {
```
Comment (jsign) [inline index/ask/ask.go]: Some API changes from updating the Louts dependency.

**Comment by asutula** [comment]
👀

File: docker/docker-compose-embedded.yaml [hunk 6]
```diff
@@ -16,7 +16,6 @@ services:
       - ipfs
     environment:
       - TEXFILTOOLS_EMBEDDED=true
-      - TEXFILTOOLS_REPOPATH=/tmp/.texfc
```
[the remark this answers is not in the document]
Comment (asutula) [reply docker/docker-compose-embedded.yaml]: awesome!

File: exe/server/main.go [hunk 7]
```diff
@@ -63,15 +63,20 @@ func main() {
...
+			repoPath = strings.Replace(repoPath, "${HOME}", home, -1)
+		}
+	} else {
+		repoPath, err = ioutil.TempDir("", ".texfc-*")
 		if err != nil {
-			log.Fatalf("error when setting default repo path to home dir: %s", err)
+			log.Fatal(err)
 		}
-		repoPath = strings.Replace(repoPath, "${HOME}", home, -1)
 	}
```
[the remark this answers is not in the document]
Comment (jsign) [reply exe/server/main.go]: Yeah, I know what are you referring to.  But this change avoids that error.
A bit more detail on the situation:
When the embeded network is run, the Lotus node uses `os.TempDir()` as its base path for the repo. Since this solution in `--embedded` mode also uses `os.TempDir()`, that constrain of using the same  _IPFS_PATH_ holds correctly.

File: api/server/server.go [hunk 8]
```diff
@@ -161,8 +172,12 @@ func NewServer(conf Config) (*Server, error) {
 		return nil, fmt.Errorf("creating ipfs client: %s", err)
 	}
 
-	reptop := reptop.New(rm, ai)
-	fpamanager, err := fpa.New(txndstr.Wrap(ds, "fpa"), wm, dm, reptop, &noopauditor.Auditor{}, ipfs)
+	cl := filcold.New(reptop.New(rm, ai), dm, ipfs.Dag())
+	hl := coreipfs.New(ipfs)
```
[the remark this answers is not in the document]
Comment (jsign) [reply api/server/server.go]: Totally agree. Also, it may be good to group dependency graph creation in methods that explain a bit better what _modules_ are being created. e.g: `bootstrapFPA(..)` with all that sub packages creating and wiring.

File: fpa/fastapi/fastapi.go [hunk 9]
```diff
@@ -2,208 +2,294 @@ package fastapi
...
+	for _, jid := range jids {
+		j, err := i.sched.GetJob(jid)
+		if err == scheduler.ErrNotFound {
+			continue
+		}
+		if err != nil {
+			i.watchers = i.watchers[:len(i.watchers)-1]
+			close(ch)
+			return nil, fmt.Errorf("getting current job state: %s", err)
+		}
```
[the remark this answers is not in the document]
Comment (jsign) [reply fpa/fastapi/fastapi.go]: Uhm, I'm not sure I understood correctly. But taking a look at this now I see some things I don't like, which maybe some of them are what you're refering to.

Sounds like a better thing would be:
1. First get all selected jobs current state. And also cover the case if that variadic is empty, which means *all*. That case isn't handled correctly now.
2. Then add the watcher to `i.watchers`
3. Then send gathered current states to the channel.

This avoids some things in this impl:
- Having to do that slice removing if `err != nil`.
- Avoid sending job states to the channel if the Watch() operation can fail on gathering a further Job current state.

I'll make that change. Confirm if I'm missing what you're refering to!

File: fpa/filcold/filcold.go [hunk 10]
```diff
@@ -0,0 +1,119 @@
+package filcold
+
+import (
+	"context"
+	"fmt"
+	"io"
+
+	"github.com/filecoin-project/go-fil-markets/storagemarket"
+	"github.com/ipfs/go-car"
```
[the remark this answers is not in the document]
Comment (jsign) [reply fpa/filcold/filcold.go]: Oh, cool. Will do.

File: fpa/minerselector/fixed/fixed.go [hunk 11]
```diff
@@ -3,31 +3,34 @@ package fixed
...
 func New(addr string, epochPrice uint64) *FixedMinerSelector {
 	return &FixedMinerSelector{
 		addr:       addr,
 		epochPrice: epochPrice,
 	}
 }
 
-func (fms *FixedMinerSelector) GetTopMiners(n int) ([]types.MinerProposal, error) {
+// GetTopMiners returns the single allowed miner in the selector.
+func (fms *FixedMinerSelector) GetTopMiners(n int) ([]fpa.MinerProposal, error) {
```
[the remark this answers is not in the document]
Comment (jsign) [reply fpa/minerselector/fixed/fixed.go]: Agree, will change.

File: fpa/fastapi/fastapi.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (jsign) [reply fpa/fastapi/fastapi.go]: Also, in that case that the job isn't found I think it's better to return as an error since it would be very weird to receive a job id that we don't have.

**Comment by jsign** [comment]
> Left a few comments, questions, and nits, but this looks great. Persistent job queues and processing are some of the hardest code I've had to write, this looks like a great implementation.

Yep, has some interesting things to consider. In particular if you resume a failed job in a particular state, since partial execution of the logic between states happened... and recovering correctly from that depends on a lot of things. 

I pushed suggested changes. Thanks for the review!

I'll merge on Monday to give a bit more time if @sander wants to take a quick look.

File: exe/server/main.go [hunk 12]
```diff
@@ -64,15 +64,20 @@ func main() {
 		if err != nil {
 			log.Fatal(err)
 		}
-	}
 
-	repoPath := config.GetString("repopath")
-	if repoPath == "${HOME}/.texfc" {
-		home, err := os.UserHomeDir()
+		repoPath := config.GetString("repopath")
+		if repoPath == "${HOME}/.texfc" {
```
Comment (sanderpick) [inline exe/server/main.go]: Should `~` also be considered? https://github.com/mitchellh/go-homedir can be handy.

File: fpa/coreipfs/coreipfs.go [hunk 13]
```diff
@@ -0,0 +1,79 @@
...
+func (ci *CoreIpfs) Pin(ctx context.Context, c cid.Cid) (fpa.HotInfo, error) {
+	log.Infof("pinning %s", c)
+	var i fpa.HotInfo
+	pth := path.IpfsPath(c)
+	ctx, cancel := context.WithTimeout(ctx, time.Second*30)
+	defer cancel()
+	if err := ci.ipfs.Pin().Add(ctx, pth, options.Pin.Recursive(true)); err != nil {
+		return i, fmt.Errorf("pinning cid %s: %s", c, err)
+	}
+	stat, err := ci.ipfs.Block().Stat(ctx, pth)
```
Comment (sanderpick) [inline fpa/coreipfs/coreipfs.go]: Nice, exploring all the wild and hidden IPFS APIs!

File: fpa/fastapi/types.go [hunk 14]
```diff
@@ -1,72 +1,51 @@
...
+	// ErrCidConfigNotFound returned when cid configuration doesn't exist in
+	// ConfigStore.
+	ErrCidConfigNotFound = errors.New("cid config not found")
+	// ErrCidInfoNotFound returned if no storing state exists for a Cid.
+	ErrCidInfoNotFound = errors.New("the cid doesn't have any saved state")
 )
 
-type ID string
+// ConfigStore is a repository for all state of a FastAPI.
+type ConfigStore interface {
```
Comment (sanderpick) [inline fpa/fastapi/types.go]: 👍 An additional selling point for the interface: some remote DB with backup capabilities.

File: fpa/filcold/filcold.go [hunk 15]
```diff
@@ -0,0 +1,119 @@
...
+		}
+	}
+	log.Infof("done")
+	return filstrg, nil
+}
+
+func ipldToFileTransform(ctx context.Context, dag format.DAGService, c cid.Cid) io.Reader {
+	r, w := io.Pipe()
+	go func() {
+		if err := car.WriteCar(ctx, dag, []cid.Cid{c}, w); err != nil {
```
Comment (sanderpick) [inline fpa/filcold/filcold.go]: 👍

File: fpa/grpc/service.go [hunk 16]
```diff
@@ -138,12 +161,28 @@ func (s *Service) AddFile(srv pb.API_AddFileServer) error {
 
 	go receiveFile(srv, writer)
 
-	cid, err := i.AddFile(srv.Context(), reader)
```
[the remark this answers is not in the document]
Comment (sanderpick) [reply fpa/grpc/service.go]: Hopefully it would still work with two different hot layer... as in, the content would be discoverable.

File: fpa/grpc/service.go [hunk 17]
```diff
@@ -138,12 +161,28 @@ func (s *Service) AddFile(srv pb.API_AddFileServer) error {
...
+	c, err := s.hot.Add(srv.Context(), reader)
+	if err != nil {
+		return fmt.Errorf("adding data to hot layer: %s", err)
+	}
+
+	jid, err := i.AddCid(c)
 	if err != nil {
 		return err
 	}
+	ch, err := i.Watch(jid)
```
Comment (sanderpick) [inline fpa/grpc/service.go]: So here, we're blocking and watching the job internally, but in the future the caller would receive these job events?

File: fpa/integrationtest/integration_test.go [hunk 18]
```diff
@@ -0,0 +1,302 @@
...
+func TestMain(m *testing.M) {
+	logging.SetAllLoggers(logging.LevelError)
+
+	// logging.SetLogLevel("scheduler", "debug")
+	// logging.SetLogLevel("fastapi", "debug")
+	// logging.SetLogLevel("jobstore", "debug")
+	// logging.SetLogLevel("coreipfs", "debug")
+
+	var cls func()
+	ipfsDocker, cls = tests.LaunchDocker()
```
Comment (sanderpick) [inline fpa/integrationtest/integration_test.go]: 😄

File: fpa/interfaces.go [hunk 19]
```diff
@@ -0,0 +1,52 @@
...
+	GetFromHot(ctx context.Context, c cid.Cid) (io.Reader, error)
+	GetJob(JobID) (Job, error)
+
+	Watch(InstanceID) <-chan Job
+	Unwatch(<-chan Job)
+}
+
+// HotLyer is a fast datastorage layer for storing and retrieving raw
+// data or Cids.
+type HotLayer interface {
```
Comment (sanderpick) [inline fpa/interfaces.go]: Wondering, maybe these should be `HotStorage` and `ColdStorage`? The word "layer" doesn't describe much about what it is.

File: fpa/minerselector/reptop/reptop.go [hunk 20]
```diff
@@ -3,41 +3,47 @@ package reptop
...
 
-	"github.com/textileio/fil-tools/fpa/types"
+	"github.com/textileio/fil-tools/fpa"
 	"github.com/textileio/fil-tools/index/ask"
 	"github.com/textileio/fil-tools/reputation"
 )
 
+// RepTop is a fpa.MinerSelector implementation that returns the top N
+// miners from a Reputations Module and an Ask Index.
 type RepTop struct {
```
Comment (sanderpick) [inline fpa/minerselector/reptop/reptop.go]: Slick

File: fpa/interfaces.go [hunk 21]
```diff
@@ -0,0 +1,52 @@
...
+	NewWallet(ctx context.Context, typ string) (string, error)
+	Balance(ctx context.Context, addr string) (uint64, error)
+}
+
+// Scheduler creates and manages Job which executes Cid configurations
+// in Hot and Cold layers, enables retrieval from those layers, and
+// allows watching for Job state changes.
+type Scheduler interface {
+	Enqueue(CidConfig) (JobID, error)
+	GetFromHot(ctx context.Context, c cid.Cid) (io.Reader, error)
```
Comment (sanderpick) [inline fpa/interfaces.go]: `GetCidFromHot` ?

File: fpa/interfaces.go [hunk 22]
```diff
@@ -0,0 +1,52 @@
...
+type WalletManager interface {
+	NewWallet(ctx context.Context, typ string) (string, error)
+	Balance(ctx context.Context, addr string) (uint64, error)
+}
+
+// Scheduler creates and manages Job which executes Cid configurations
+// in Hot and Cold layers, enables retrieval from those layers, and
+// allows watching for Job state changes.
+type Scheduler interface {
+	Enqueue(CidConfig) (JobID, error)
```
Comment (sanderpick) [inline fpa/interfaces.go]: `EnqueueCid`?

File: fpa/scheduler/scheduler.go [hunk 23]
```diff
@@ -0,0 +1,173 @@
...
+				log.Infof("job %s executed with final state %d and errcause %q", j.ID, j.Status, j.ErrCause)
+				if err := s.store.Put(j); err != nil {
+					log.Errorf("saving job %s: %s", j.ID, err)
+				}
+			}
+		}
+	}
+}
+
+func (s *Scheduler) execute(ctx context.Context, job *fpa.Job) error {
```
Comment (sanderpick) [inline fpa/scheduler/scheduler.go]: Nice and clean 😄

File: fpa/grpc/service.go (hunk 17 above)
Comment (jsign) [reply fpa/grpc/service.go]: Yep, now does this internally just to not change the gRPC APIs and CLI... but after having a more stable internal API, sound better to let the client watch to whatever might be interested.

File: fpa/interfaces.go (hunk 19 above)
Comment (jsign) [reply fpa/interfaces.go]: Yeah, I agree. _Layer_ sounds much more abstract of what this is describing. 
Will change this in the next PR 👍

File: fpa/interfaces.go (hunk 21 above)
Comment (jsign) [reply fpa/interfaces.go]: Agree, wil change in next pr!

File: fpa/interfaces.go (hunk 22 above)
Comment (jsign) [reply fpa/interfaces.go]: Yeah, sounds better. I'll also see how the _unfreeze_ action fits in the api parameters and names... since it sounds that the parameter should be of a different type of _CidConfig_.

Sounds I'd prefer avoid `Enqueue(interface{})` to accept different config types... better to have two apis than start with the type-checking world. So, a priori this change sounds good, will do in next pr.

**Comment by jsign** [comment]
Thanks for the review. 
I'll let the renamings to the next PR, which will have other renamings that are in-progress to confirm.

File: exe/server/main.go (hunk 12 above)
Comment (jsign) [reply exe/server/main.go]: Left this in my mind and forgot to comment.
Do you mean having the default be `~/.texfc` and using `go-homedir`?
That sounds pretty cool, will add that change to the next changes.
