### PR TITLE
jsonrpc autoconnect, indexes client recovery, docker volumes, bugfixes

### LINKED ISSUE #41: lotus/client: reconnect on failure
If the connection with the lotus client fails (e.g: lotus is restarted), things should keep moving forward retrying or similar.

### LINKED ISSUE #67: docker: user map repo to volume

### PR DESCRIPTION
**Pull request by jsign**
While running our reputation index, which is a long-running thing, the lotus client was kind of fatal when the websocket connection was lost. This was a known thing for a while in the `jsonrpc` from lotus, so I jumped to help us both in that (https://github.com/filecoin-project/lotus/pull/1155).
The current solution that is in this PR, is more in line with a previous PR than the mentioned before... so it may change again with my new solution, but the current one is enough for our interests.

While installing and leaving running the service in the cloud instance, I discovered a set of issues or needed improvements to keep it more: reliable on lotus or self crashes, tested the persistence of indexed data and recovery after restarting, and some extra tunes to dockerized things that run on the cloud (and I also use locally to test things, since helps fast iteration with the many wires to connect).

I'll make some comments, but that's pretty much the summary of this.

Closes #41 
Closes #67

### CODE REVIEW

File: cmd/server/main.go [hunk 1]
```diff
@@ -78,3 +81,9 @@ func instrumentationSetup() {
 		}
 	}()
 }
+
+func pprofSetup() {
```
Comment (jsign) [inline cmd/server/main.go]: Enabled pprof. I wanted to inspect some things about a memprofile of the service. 
All good. Left it here anyways, is binded to `localhost` so not public.

File: docker/docker-compose.yaml [hunk 2]
```diff
@@ -10,7 +13,10 @@ services:
       - TEXTILE_LOTUS_TOKEN=${TEXTILE_LOTUS_TOKEN}
     ports:
       - 8888:8888
+      - 6060:6060
     restart: always
+    volumes:
+      - textile-fc-data:/root/.texfc
```
Comment (jsign) [inline docker/docker-compose.yaml]: Made a change in the docker-compose used to launch the server, prometheus, grafana, etc.
The `textile-fc` (our service) uses a volume to map the repo folder to a Docker volume. Mostly for saving progress while restarting the compose environment, and tests index persistence.

File: docker/grafana/provisioning/dashboards/TextileFC.json [hunk 3]
```diff
@@ -523,7 +523,7 @@
       ],
```
Comment (jsign) [inline docker/grafana/provisioning/dashboards/TextileFC.json]: Some improvements in clarity and new boxes that helped discover some things.

File: index/miner/meta.go [hunk 4]
```diff
@@ -151,33 +150,3 @@ func (mi *MinerIndex) persistMetaIndex(index MetaIndex) error {
 	}
 	return nil
 }
-
```
Comment (jsign) [inline index/miner/meta.go]: Moved to `miners.go` since loading from store is a general thing.

File: index/miner/miner.go [hunk 5]
```diff
@@ -153,10 +154,11 @@ func (mi *MinerIndex) Close() error {
 // miners.
 func (mi *MinerIndex) start() {
 	defer func() { mi.finished <- struct{}{} }()
-	n, err := mi.api.ChainNotify(mi.ctx)
```
Comment (jsign) [inline index/miner/miner.go]: Stop using `ChainNotify` for _listening_ to the chain.
I've been thinking about this for quite some time since puts a lot of stress. It notifies about every possible forks that might happen in 10-20s time frame... we're only interested in the heaviest tipset known and let time (and lotus) decide which are the heaviest ones.

Switched to waiting the avg tipset time and just asking for the heaviest current tipset (which is what we need). Mini forks or possible future forks aren't interesting.  We don't need to be at the bleeding-edge of that.

File: index/miner/onchain.go [hunk 6]
```diff
@@ -12,28 +12,48 @@ import (
...
+	hOffset = uint64(5)
 )
 
-// updateOnChainIndex updates on-chain index information when a new tipset
-func (mi *MinerIndex) updateOnChainIndex(new *types.TipSet) error {
+// updateOnChainIndex updates on-chain index information in the direction of heaviest tipset
+// with some height offset to reduce sensibility to reorgs
+func (mi *MinerIndex) updateOnChainIndex() error {
 	log.Info("updating on-chain index...")
+	heaviest, err := mi.api.ChainHead(mi.ctx)
```
Comment (jsign) [inline index/miner/onchain.go]: Since we don't use `ChainNotify` anymore, we call `ChainHead` which returns the current accepted heaviest tipset known (what's considered _the truth_ now).

File: index/miner/onchain.go [hunk 7]
```diff
@@ -12,28 +12,48 @@ import (
...
 	ts, err := mi.store.LoadAndPrune(mi.ctx, newtsk, &chainIndex)
 	if err != nil {
-		return err
+		return fmt.Errorf("error getting last saved from store: %s", err)
 	}
 	if chainIndex.Power == nil {
 		chainIndex.Power = make(map[string]Power)
 	}
+	hdiff := new.Height - chainIndex.LastUpdated
+	if hdiff == 0 {
```
Comment (jsign) [inline index/miner/onchain.go]: A simple check to avoid doing some unnecessary work if the heaviest things is the same as the last known one.

File: index/slashing/slashing.go [hunk 8]
```diff
@@ -123,42 +129,45 @@ func (s *SlashingIndex) Close() error {
 // start is a long running job that keeps the index up to date with chain updates
 func (s *SlashingIndex) start() {
 	defer close(s.finished)
-	n, err := s.api.ChainNotify(s.ctx)
```
Comment (jsign) [inline index/slashing/slashing.go]: Same idea of changing `ChainNotify` with `ChainHead` in this index.

File: index/slashing/slashing.go [hunk 9]
```diff
@@ -200,15 +210,12 @@ func updateFromPath(ctx context.Context, api API, index *Index, path []*types.Ti
...
-			if !ok {
-				info = Slashes{}
-				index.Miners[addr] = info
-			}
+			info := index.Miners[addr]
 			if len(info.Epochs) > 0 && info.Epochs[len(info.Epochs)-1] == patch[addr] {
 				continue
 			}
 			info.Epochs = append(info.Epochs, patch[addr])
+			index.Miners[addr] = info
```
Comment (jsign) [inline index/slashing/slashing.go]: Bug fix. `info` was edited but not assigned to current index (so lost changes).

File: lotus/client.go [hunk 10]
```diff
@@ -61,7 +61,7 @@ func New(maddr ma.Multiaddr, authToken string) (*API, func(), error) {
 	closer, err := jsonrpc.NewMergeClient("ws://"+addr+"/rpc/v0", "Filecoin",
 		[]interface{}{
 			&api.Internal,
-		}, headers)
+		}, headers, jsonrpc.WithReconnect(true, time.Second*3, 0))
```
Comment (jsign) [inline lotus/client.go]: Original PR that I did for lotus. You can configure a interval time to wait so that the websocket connection is recovered, adn the client can still use it as "nothing happened".

In the newer PR that will get merged, you can annotate with `retry:"true"` methods of the API. If that annotation is detected, the client retries itself the call until having success on a recovered connection. This makes the client even do less work since shouldn't do any kind of retry logic.

I may eventually consider switching to the new solution.

File: lotus/client.go [hunk 11]
```diff
@@ -242,16 +242,10 @@ func monitorLotusSync(ctx context.Context, c *API) {
 }
 
 func refreshHeightMetric(ctx context.Context, c *API) {
-	var h uint64
-	state, err := c.SyncState(ctx)
+	heaviest, err := c.ChainHead(ctx)
```
Comment (jsign) [inline lotus/client.go]: Simplify `curent height` metric in grafana dashboard to the current heaviest tipset... not the newer _potential_ new tipset that we discovered recently.

File: lotus/jsonrpc/client.go [hunk 12]
```diff
@@ -85,12 +85,21 @@ type client struct {
```
Comment (jsign) [inline lotus/jsonrpc/client.go]: `lotus/jsonrpc` package is from Lotus. Has the changes proposed for autoconnect feature.
Can be dismissed for review... but if like crazy things might be fun.

File: util/util.go [hunk 13]
```diff
@@ -2,10 +2,15 @@ package util
 
 import (
 	"fmt"
+	"time"
 
 	ma "github.com/multiformats/go-multiaddr"
 )
 
+const (
+	AvgBlockTime = time.Second * 30
```
Comment (jsign) [inline util/util.go]: In testnet is 45s. But in mainet will be 30s as mentioned in the spec.
Leaving 30s here since updating more often doesn't hurt; worst thing that can happen is doing nothing.

**Comment by jsign** [comment]
Will DCO after review just in case that might not invalidate review comments.

File: index/miner/meta.go [hunk 14]
```diff
@@ -50,6 +49,7 @@ func (mi *MinerIndex) metaWorker() {
 			newIndex, err := updateMetaIndex(mi.ctx, mi.api, mi.h, mi.lr, addrs)
 			if err != nil {
 				log.Errorf("error when updating meta index: %s", err)
+				break
```
Comment (jsign) [inline index/miner/meta.go]: If for some reason generating a new index fails, log the error and break here. If we continue we would override the current-good-state-index with an empty one and lost things. Better to keep it outdated than to lose it.

File: index/miner/miner.go [hunk 15]
```diff
@@ -100,7 +101,9 @@ func (mi *MinerIndex) Get() Index {
 	defer mi.lock.Unlock()
 	ii := Index{
 		Meta: MetaIndex{
-			Info: make(map[string]Meta, len(mi.index.Meta.Info)),
+			Online:  mi.index.Meta.Online,
+			Offline: mi.index.Meta.Offline,
```
Comment (jsign) [inline index/miner/miner.go]: These copies were missing so didn't appear correctly in the output.

**Comment by jsign** [comment]
Rebased.
