### PR TITLE
Use ldevnet for tests, Docker fixes, GH Action improv., extend Readme, many misc fixes

### LINKED ISSUE #90: Readme: include Server description and information

### LINKED ISSUE #91: ldevnet: use it in all tests that require real Lotus node

### LINKED ISSUE #92: GH Actions: adjust yaml to Lotus dependencies
Now that code have Lotus dependencies, such OpenCL or Rust compiling, make necessary adjustments and let all full-blown tests run in CI.

### LINKED ISSUE #93: docker: fix Dockerfiles and Compose to new dependencies
New dependencies should be considered for Docker ecosystem:
- Embed necessary files in the executable
- Install new dependencies

### PR DESCRIPTION
**Pull request by jsign**
Continuation in the line of work of #79.
The main intention of this PR is leveraging #79 work to switch existing tests to use the created `ldevnet` package instead of requiring a real running Lotus node. Changed tests involve Deals Module functionality (yes, making deals), and all reputation indexes. 

Using ldevnet makes sense for more Store and Retrieve functionalities which we haven't mature that much since we didn't have a good environment to make much real progress. So, that might change now that we can start building more in that direction. For reputation indexes its OK, but not that much fun since it would require a richer environment with multiple miners, some of them online/offline, with different setups, slashing, etc. Despite that, some coverage can be done.

It turns out that adding Lotus as a dependency created a lot of challenges and side-effects. Which is quite tedious to describe here. I'll add comments in the review to help understand some seemingly weird changes. Nothing comes for free, but being able to have the chance to have more testings I think may worth it (but doubted about that multiple times in the process).

The big TL;DR: all tests that required a real Lotus node running use a local devnet. All this runs by GH Actions correctly.

Closes #90, Closes #91, Closes #92, Closes #93

### CODE REVIEW

File: build/parameters.go [hunk 1]
```diff
@@ -0,0 +1,7 @@
+package build
```
Comment (jsign) [inline build/parameters.go]: The last backfire from importing Lotus. It should embed a parameters.json file in the executable because some `init()` function in some package checks it.  Also a PITA... but thankfully this isn't important for anything else. 

These nifty things are dealt with by the Dockerfiles already, or some other tooling as Makefile. 
I thought about forking Lotus and adjusting things to avoid this stuff, but that should be well worth since would mean maintaining our own fork with changes and updating it with some frequency. 

At the moment, chose to avoid that. Seeing the big picture of this PR, there are only 2 things that are weird: faking proof files, and embedding this thing. So, it isn't that bad to take such drastic decision.

File: chainsync/chainsync_test.go [hunk 2]
```diff
@@ -2,29 +2,28 @@ package chainsync
```
Comment (jsign) [inline chainsync/chainsync_test.go]: Make existing test that needed a real lotus running, use the ldevnet.

File: deals/deals.go [hunk 3]
```diff
@@ -30,28 +26,8 @@ var (
...
-}
-
-// DealConfig contains information about a proposal for a particular miner
-type DealConfig struct {
-	Miner      string
-	EpochPrice types.BigInt
-}
-
-// DealInfo contains information about a proposal storage deal
-type DealInfo struct {
```
Comment (jsign) [inline deals/deals.go]: Moved to `type.go` file.

File: deals/deals.go [hunk 4]
```diff
@@ -63,47 +39,52 @@ type API interface {
...
 
 // New creates a new deal module
-func New(ds datastore.Datastore, api API) *Module {
-	// can't avoid home base path, ipfs checks: cannot add filestore references outside ipfs root (home folder)
-	home := os.TempDir()
-	os.MkdirAll(filepath.Join(home, "textilefc"), os.ModePerm)
-	dm := &Module{
-		api:            api,
-		basePathImport: filepath.Join(home, "textilefc"),
+func New(api API, opts ...Option) (*Module, error) {
```
Comment (jsign) [inline deals/deals.go]: As usual with tests, some refactoring to allow better config of things.

File: deals/deals_test.go [hunk 5]
```diff
@@ -21,35 +23,102 @@ func TestMain(m *testing.M) {
...
-	checkErr(t, err)
-	defer dnet.Close()
-
-	m := New(tests.NewTxMapDatastore(), dnet.Client)
+func TestStore(t *testing.T) {
+	numMiners := []int{1}
+	for _, nm := range numMiners {
+		t.Run(fmt.Sprintf("CantMiners%d", nm), storeMultiMiner(t, nm))
+	}
+}
```
Comment (jsign) [inline deals/deals_test.go]: This tests using our Deals Module to make a deal and check that makes all the process until fully active.
Mostly, all this PR (and #79 ) was to have this working.

File: deals/deals_test.go [hunk 6]
```diff
@@ -21,35 +23,102 @@ func TestMain(m *testing.M) {
...
 
-func TestStoreSimple(t *testing.T) {
-	t.Parallel()
-	dnet, err := ldevnet.New(t, 1)
-	checkErr(t, err)
-	defer dnet.Close()
-
-	m := New(tests.NewTxMapDatastore(), dnet.Client)
+func TestStore(t *testing.T) {
+	numMiners := []int{1}
```
Comment (jsign) [inline deals/deals_test.go]: Left this quite generic if I manage later to have the ldevnet working for more than one miner. So that would be interesting to extend.

File: deals/deals_test.go [hunk 7]
```diff
@@ -21,35 +23,102 @@ func TestMain(m *testing.M) {
...
+	for _, nm := range numMiners {
+		t.Run(fmt.Sprintf("CantMiners%d", nm), storeMultiMiner(t, nm))
+	}
+}
 
+func TestWatchStore(t *testing.T) {
```
Comment (jsign) [inline deals/deals_test.go]: Test for the `Watch` API from Deals Module to see changes in Deals state.

File: exe/fil-tools/cmd/deals_store.go [hunk 8]
```diff
@@ -54,8 +54,8 @@ var storeCmd = &cobra.Command{
 		}
 
 		file, err := os.Open(path)
-		defer file.Close()
 		checkErr(err)
+		defer file.Close()
```
Comment (jsign) [inline exe/fil-tools/cmd/deals_store.go]: Bugfix in the wild.

File: exe/server/Dockerfile [hunk 9]
```diff
@@ -1,17 +1,16 @@
...
-RUN GOOS=linux go build -o main exe/server/main.go
+RUN GOOS=linux go build -o main exe/server/main.go && \
+go run github.com/GeertJohan/go.rice/rice append --exec main -i ./build
 
-FROM alpine
-RUN apk --no-cache add ca-certificates wget && \
-    wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
-    wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.28-r0/glibc-2.28-r0.apk && \
-    apk add glibc-2.28-r0.apk
+FROM ubuntu
```
Comment (jsign) [inline exe/server/Dockerfile]: No more `alpine`. Tried to setup necessary dependencies but for one reason or another couldn't. 
TBH, also never compared how big was alpine after adding glibc... so maybe wasn't that minimal at all.
Anyway, maybe rooms for some MB improvements here, but is in the order of ~60MB.

File: exe/server/Dockerfile [hunk 10]
```diff
@@ -1,17 +1,16 @@
...
 RUN mkdir /app 
 WORKDIR /app 
-COPY go.mod go.sum ./
 COPY extern extern
+COPY go.mod go.sum ./
 RUN go mod download
 COPY . . 
-RUN GOOS=linux go build -o main exe/server/main.go
+RUN GOOS=linux go build -o main exe/server/main.go && \
+go run github.com/GeertJohan/go.rice/rice append --exec main -i ./build
```
Comment (jsign) [inline exe/server/Dockerfile]: The _interesting_ part of embedding the `parameter.json` file in the executable.

File: index/ask/ask_test.go [hunk 11]
```diff
@@ -2,28 +2,41 @@ package ask
...
+	logging "github.com/ipfs/go-log/v2"
 	"github.com/textileio/filecoin/tests"
 )
 
+func TestMain(m *testing.M) {
+	logging.SetAllLoggers(logging.LevelError)
+	os.Exit(m.Run())
+}
+
 func TestFreshBuild(t *testing.T) {
```
Comment (jsign) [inline index/ask/ask_test.go]: Make ask index test use a ldevnet instead of real Lotus running.

File: index/miner/meta.go [hunk 12]
```diff
@@ -65,7 +64,7 @@ func (mi *MinerIndex) metaWorker() {
 
 // updateMetaIndex generates a new index that contains fresh metadata information
 // of addrs miners.
-func updateMetaIndex(ctx context.Context, api API, h *fchost.FilecoinHost, lr iplocation.LocationResolver, addrs []string) (MetaIndex, error) {
+func updateMetaIndex(ctx context.Context, api API, h P2PHost, lr iplocation.LocationResolver, addrs []string) (MetaIndex, error) {
```
Comment (jsign) [inline index/miner/meta.go]: Switched from concrete impl, to interface for help testing.

File: index/miner/miner_test.go [hunk 13]
```diff
@@ -1,35 +1,73 @@
...
+func TestMain(m *testing.M) {
+	cbor.RegisterCborType(time.Time{})
+	util.AvgBlockTime = time.Millisecond * 10
+	metadataRefreshInterval = time.Millisecond * 10
+	logging.SetAllLoggers(logging.LevelError)
+	logging.SetLogLevel("index-miner", "debug")
+	os.Exit(m.Run())
+}
+
 func TestFullRefresh(t *testing.T) {
```
Comment (jsign) [inline index/miner/miner_test.go]: Make miner index test use a ldevnet instead of real Lotus running.

File: index/miner/onchain.go [hunk 14]
```diff
@@ -52,8 +52,8 @@ func (mi *MinerIndex) updateOnChainIndex() error {
 
 	mctx := context.Background()
 	start := time.Now()
-	log.Infof("current state height %d, new tipset height %d", chainIndex.LastUpdated, new.Height)
-	if hdiff > fullThreshold {
+	log.Infof("current state height %d, new tipset height %d", chainIndex.LastUpdated, new.Height())
+	if hdiff > fullThreshold || chainIndex.LastUpdated == 0 {
```
Comment (jsign) [inline index/miner/onchain.go]: Bugfix revealed by tests

File: index/slashing/slashing_test.go [hunk 15]
```diff
@@ -1,32 +1,41 @@
...
 )
 
+func TestMain(m *testing.M) {
+	util.AvgBlockTime = time.Millisecond * 10
+	logging.SetAllLoggers(logging.LevelError)
+	logging.SetLogLevel("index-miner", "debug")
+	os.Exit(m.Run())
+}
+
 func TestFreshIndex(t *testing.T) {
```
Comment (jsign) [inline index/slashing/slashing_test.go]: Make slashing index test use a ldevnet instead of real Lotus running.

File: ldevnet/ldevnet.go [hunk 16]
```diff
@@ -28,20 +28,20 @@ import (
...
+	"github.com/libp2p/go-libp2p-core/crypto"
+	"github.com/libp2p/go-libp2p-core/peer"
 	mocknet "github.com/libp2p/go-libp2p/p2p/net/mock"
 	"github.com/stretchr/testify/require"
 )
 
 func init() {
 	build.SectorSizes = []uint64{1024}
 	build.MinimumMinerPower = 1024
+	os.Setenv("TRUST_PARAMS", "1")
```
Comment (jsign) [inline ldevnet/ldevnet.go]: ENV var used by Lotus code to avoid checking the checksum of proof files. This makes our `touch`ed fake files not be considered invalid.

File: ldevnet/ldevnet.go [hunk 17]
```diff
@@ -28,20 +28,20 @@ import (
...
 }
 
 type LocalDevnet struct {
```
Comment (jsign) [inline ldevnet/ldevnet.go]: From here below, some extra hacks to code inherited from Lotus with some changes to make it useful for us.

File: lotus/client_test.go [hunk 18]
```diff
@@ -21,7 +21,6 @@ func TestMain(m *testing.M) {
 }
 
 func TestClientVersion(t *testing.T) {
```
Comment (jsign) [inline lotus/client_test.go]: Despite we could run ldevnets in parallel for tests (which is nice), they're quite intensive. 
Don't be so bad and run them serially.

File: tests/ldevnet.go [hunk 19]
```diff
@@ -0,0 +1,34 @@
...
+	"github.com/filecoin-project/go-address"
+	"github.com/filecoin-project/lotus/build"
+	"github.com/textileio/filecoin/ldevnet"
+)
+
+func init() {
+	build.InsecurePoStValidation = true
+}
+
+func CreateLocalDevnet(t *testing.T, numMiners int) (*ldevnet.LocalDevnet, address.Address, []address.Address, func()) {
```
Comment (jsign) [inline tests/ldevnet.go]: Some helper for tests.

File: util/util.go [hunk 20]
```diff
@@ -7,7 +7,7 @@ import (
 	ma "github.com/multiformats/go-multiaddr"
 )
 
-const (
+var (
```
Comment (jsign) [inline util/util.go]: So can be tuned by tests.

File: README.md [hunk 21]
```diff
@@ -37,6 +37,38 @@ chmod +x filecoin
 
 Try `filecoin --help`.
 
+### Server
```
[the remark this answers is not in the document]
Comment (jsign) [reply README.md]: cc @andrewxhill ; to know about some extra info was added here.

File: build/parameters.go [hunk 22]
```diff
@@ -0,0 +1,7 @@
...
+
+import rice "github.com/GeertJohan/go.rice"
```
Comment (asutula) [inline build/parameters.go]: cool module

File: deals/deals_test.go [hunk 23]
```diff
@@ -21,35 +23,102 @@ func TestMain(m *testing.M) {
...
+			if err != nil {
+				return err
+			}
+			if di.State == api.DealComplete {
+				return nil
+			}
+			if di.State != api.DealUnknown &&
+				di.State != api.DealAccepted &&
+				di.State != api.DealStaged &&
+				di.State != api.DealSealing {
```
Comment (asutula) [inline deals/deals_test.go]: Cool, these constants exist now?!

File: exe/fil-tools/cmd/deals_store.go (hunk 8 above)
Comment (asutula) [reply exe/fil-tools/cmd/deals_store.go]: thx

Comment (asutula) [reply exe/fil-tools/cmd/deals_store.go]: Although, I guess my thinking was that the file should be closed even if there is an error. In the case of an error, this change would cause the the program to exit before closing the file (not sure this is even a problem).

File: deals/deals_test.go (hunk 23 above)
Comment (asutula) [reply deals/deals_test.go]: Oh, those are part of lotus

File: exe/fil-tools/cmd/deals_store.go (hunk 8 above)
Comment (jsign) [reply exe/fil-tools/cmd/deals_store.go]: Actually, it wouldn't because the file can't be considered open since the operation failed.

Making calls on return values from failed operations most probably will result in panics or other errors. When an operation fails, we can't consider return values (other than err) to be valid.

File: deals/deals_test.go (hunk 23 above)
Comment (jsign) [reply deals/deals_test.go]: Yes. From the API POV, these names are returned in the `DealInfo.StateName` attribute.

**Comment by jsign** [comment]
I'll merge this to allow deploying the last version to the cloud instance, so to allow @asutula work in other direction. Anyone feel free to add any extra comment.
